# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: migueldeveloper
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-node-aws

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource:
            - 'arn:aws:dynamodb:us-east-2:640168448281:table/PeopleTable'

functions:
  hello:
    handler: src/handlers/handler.welcome
    events:
      - httpApi:
          path: /
          method: get
  getPeople:
    handler: src/handlers/peopleHandler.getPeopleHandler
    events:
      - httpApi:
          path: /people
          method: get
  getFimls:
    handler: src/handlers/filmsHandler.getFimlsHandler
    events:
      - httpApi:
          path: /films
          method: get      
  createPerson:
    handler: src/handlers/addPeopleHandler.addPeopleHandler
    events:
      - httpApi:
          path: /persons
          method: post
  showPerson:
    handler: src/handlers/showPeopleHandler.showPeopleHandler
    events:
      - httpApi:
          path: /persons
          method: get 
resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
